/** Value used for "Other (not listed)" breed/clinic dropdown rows. */
export const OTHER_LISTED_VALUE = "__OTHER_LISTED__";

export const OTHER_BREED_OPTION_LABEL = "Other (not listed)";

export const BREED_OPTIONS: Record<string, string[]> = {
  Dog: [
    // Pure breeds (alphabetical)
    "Australian Shepherd",
    "Basenji",
    "Basset Hound",
    "Beagle",
    "Bernese Mountain Dog",
    "Bichon Frise",
    "Border Collie",
    "Boston Terrier",
    "Boxer",
    "Brittany",
    "Bulldog",
    "Cane Corso",
    "Cavalier King Charles Spaniel",
    "Chihuahua",
    "Cocker Spaniel",
    "Dachshund",
    "Doberman Pinscher",
    "English Springer Spaniel",
    "French Bulldog",
    "German Shepherd",
    "German Shorthaired Pointer",
    "Golden Retriever",
    "Great Dane",
    "Havanese",
    "Irish Setter",
    "Italian Greyhound",
    "Labrador Retriever",
    "Maltese",
    "Miniature Dachshund",
    "Miniature Schnauzer",
    "Newfoundland",
    "Old English Sheepdog",
    "Papillon",
    "Pembroke Welsh Corgi",
    "Pomeranian",
    "Poodle",
    "Pug",
    "Rhodesian Ridgeback",
    "Rottweiler",
    "Saint Bernard",
    "Samoyed",
    "Shetland Sheepdog",
    "Shiba Inu",
    "Shih Tzu",
    "Siberian Husky",
    "Staffordshire Bull Terrier",
    "Vizsla",
    "Weimaraner",
    "West Highland White Terrier",
    "Whippet",
    "Yorkshire Terrier",
    // Mixed & crossbreeds (alphabetical)
    "Aussiedoodle",
    "Bernedoodle",
    "Border Collie Cross",
    "Bordoodle",
    "Cavachon",
    "Cavoodle (Cavapoo)",
    "Cockapoo",
    "Crossbreed Dog",
    "Designer Crossbreed",
    "German Shepherd Cross",
    "Golden Retriever Cross",
    "Goldendoodle",
    "Groodle",
    "Jack Russell × Fox Terrier",
    "Jug",
    "Kelpie Cross",
    "Labradoodle",
    "Labrador Cross",
    "Maltese × Poodle",
    "Maltese × Shih Tzu (Malshi)",
    "Maltipoo",
    "Mixed Breed Dog",
    "Moodle",
    "Pomsky",
    "Puggle",
    "Schnoodle",
    "Sheepadoodle",
    "Spoodle",
    "Staffy Cross",
    "Unknown Mixed Breed",
    OTHER_BREED_OPTION_LABEL,
  ],
  Cat: [
    "Abyssinian",
    "American Bobtail",
    "American Curl",
    "American Shorthair",
    "Australian Mist",
    "Balinese",
    "Bengal",
    "Bengal Cross",
    "Birman",
    "Bombay",
    "British Longhair",
    "British Shorthair",
    "British Shorthair Cross",
    "Burmese",
    "Burmese Cross",
    "Burmilla",
    "Chartreux",
    "Cornish Rex",
    "Crossbred Cat",
    "Devon Rex",
    "Domestic Cat",
    "Domestic Long Hair (DLH)",
    "Domestic Medium Hair (DMH)",
    "Domestic Short Hair (DSH)",
    "Egyptian Mau",
    "Exotic Shorthair",
    "Havana Brown",
    "Himalayan",
    "Japanese Bobtail",
    "Korat",
    "LaPerm",
    "Maine Coon",
    "Maine Coon Cross",
    "Manx",
    "Mixed Breed Cat",
    "Moggy",
    "Munchkin",
    "Norwegian Forest Cat",
    "Ocicat",
    "Oriental Longhair",
    "Oriental Shorthair",
    "Persian",
    "Persian Cross",
    "Peterbald",
    "Pixie-bob",
    "Ragamuffin",
    "Ragdoll",
    "Ragdoll Cross",
    "Russian Blue",
    "Savannah",
    "Scottish Fold",
    "Selkirk Rex",
    "Siamese",
    "Siamese Cross",
    "Siberian",
    "Singapura",
    "Snowshoe",
    "Somali",
    "Sphynx",
    "Tonkinese",
    "Toyger",
    "Turkish Angora",
    "Turkish Van",
    "Unknown Breed Cat",
    "York Chocolate",
    OTHER_BREED_OPTION_LABEL,
  ],
  Bird: [
    "African Grey Parrot",
    "Amazon Parrot",
    "Budgerigar",
    "Caique",
    "Canary",
    "Cockatiel",
    "Cockatoo",
    "Conure",
    "Eclectus Parrot",
    "Finch",
    "Galah",
    "Indian Ringneck",
    "Lorikeet",
    "Lovebird",
    "Macaw",
    "Mynah Bird",
    "Pigeon",
    "Quaker Parrot",
    "Rosella",
    "Sun Conure",
    OTHER_BREED_OPTION_LABEL,
  ],
  Rabbit: [
    "American",
    "Angora",
    "Californian",
    "Chinchilla",
    "Dutch",
    "Dwarf Lop",
    "English Lop",
    "Flemish Giant",
    "Holland Lop",
    "Lionhead",
    "Mini Rex",
    "Netherland Dwarf",
    "New Zealand",
    "Polish",
    "Rex",
    "Rhinelander",
    "Satin",
    "Silver",
    "Tan",
    "Thrianta",
    OTHER_BREED_OPTION_LABEL,
  ],
  "Guinea Pig": [
    "Abyssinian",
    "American",
    "Coronet",
    "Lunkarya",
    "Merino",
    "Peruvian",
    "Rex",
    "Ridgeback",
    "Sheba",
    "Silkie",
    "Skinny Pig",
    "Teddy",
    "Texel",
    "Thoroughbred",
    "White Crested",
    OTHER_BREED_OPTION_LABEL,
  ],
  Reptile: [
    "Ball Python",
    "Bearded Dragon",
    "Blue Tongue Lizard",
    "Boa Constrictor",
    "Carpet Python",
    "Centralian Python",
    "Chameleon",
    "Children's Python",
    "Corn Snake",
    "Eastern Blue Tongue",
    "Frilled Lizard",
    "Gecko",
    "Green Tree Python",
    "Inland Taipan",
    "Komodo Dragon",
    "Lace Monitor",
    "Olive Python",
    "Pygmy Python",
    "Shingleback Lizard",
    "Water Dragon",
    OTHER_BREED_OPTION_LABEL,
  ],
  Horse: [
    "American Quarter Horse",
    "Andalusian",
    "Appaloosa",
    "Arabian",
    "Australian Stock Horse",
    "Belgian Draft",
    "Clydesdale",
    "Friesian",
    "Hanoverian",
    "Irish Sport Horse",
    "Morgan",
    "Mustang",
    "Paint Horse",
    "Paso Fino",
    "Percheron",
    "Shetland Pony",
    "Shire",
    "Standardbred",
    "Thoroughbred",
    "Warmblood",
    OTHER_BREED_OPTION_LABEL,
  ],
  Fish: [
    "Angelfish",
    "Betta",
    "Black Moor Goldfish",
    "Clownfish",
    "Common Goldfish",
    "Discus",
    "Fantail Goldfish",
    "Gourami",
    "Guppy",
    "Koi",
    "Molly",
    "Neon Tetra",
    "Oscar",
    "Platy",
    "Plecostomus",
    "Rainbow Fish",
    "Siamese Fighting Fish",
    "Swordtail",
    "Tiger Barb",
    "Zebra Danio",
    OTHER_BREED_OPTION_LABEL,
  ],
  Other: [],
};

export function breedListForSpecies(
  sp: string,
  optionsMap: Record<string, string[]> = BREED_OPTIONS,
): { label: string; options: string[] } | null {
  const options = optionsMap[sp];
  if (!options || options.length === 0) return null;
  const label =
    sp === "Fish" || sp === "Bird" || sp === "Reptile"
      ? "Species/Type"
      : "Breed";
  return { label, options };
}

export function breedOptionSelectValue(optionLabel: string): string {
  return optionLabel === OTHER_BREED_OPTION_LABEL
    ? OTHER_LISTED_VALUE
    : optionLabel;
}
