// "Did You Know?" facts shown in the dashboard carousel.
// Each fact has two short sentences. To edit: add, remove, or change any entry below.
// Keep each fact to two sentences for consistent card sizing.

export const DID_YOU_KNOW_FACTS: { a: string; b: string }[] = [
  { a: "Cats can sleep up to 16 hours a day.", b: "All that napping helps conserve energy and supports healthy growth and repair." },
  { a: "A wagging tail doesn't always mean a dog is happy.", b: "Tail position and body language reveal much more about how they're feeling." },
  { a: "Brushing your pet's teeth can improve their overall health.", b: "Dental disease can affect the heart, kidneys, and other organs." },
  { a: "Puzzle toys are like brain games for pets.", b: "Mental stimulation can help reduce boredom and unwanted behaviours." },
  { a: "Pets can become overweight from treats alone.", b: "Treats should make up only a small part of their daily calories." },
  { a: "Microchips dramatically improve lost pet reunion rates.", b: "Keeping your contact details updated is just as important." },
  { a: "Sudden changes in behaviour may signal illness.", b: "Pets often communicate discomfort through changes in routine or mood." },
  { a: "Indoor cats need enrichment too.", b: "Toys, climbing spaces, and playtime help keep them happy and healthy." },
  { a: "Some common houseplants are toxic to pets.", b: "Lilies, aloe vera, and sago palms can all pose serious risks." },
  { a: "Regular check-ups help catch problems early.", b: "Preventive care can often avoid bigger health issues later." },
  { a: "Dogs can get sunburned.", b: "Light-coloured and short-haired breeds are especially vulnerable." },
  { a: "Cats hide pain remarkably well.", b: "Subtle changes in appetite or behaviour may be the first clues." },
  { a: "Puppies need up to 20 hours of sleep a day.", b: "Rest is essential for healthy development and learning." },
  { a: "Whiskers help pets navigate their surroundings.", b: "They're highly sensitive tools, not just cute facial features." },
  { a: "Many pets prefer routine.", b: "Consistent feeding and exercise schedules can reduce stress." },
  { a: "Dogs can become bored just like people.", b: "Daily walks and play sessions keep both body and mind active." },
  { a: "Cats usually prefer multiple water sources.", b: "Drinking more water supports urinary and kidney health." },
  { a: "Obesity is one of the most common pet health problems.", b: "Maintaining a healthy weight can add years to your pet's life." },
  { a: "Fleas can survive year-round indoors.", b: "Prevention is often easier than treatment." },
  { a: "Some pets enjoy watching television.", b: "Nature videos and moving objects can provide extra stimulation." },
  { a: "Dogs use their noses to understand the world.", b: "Their sense of smell is tens of thousands of times stronger than ours." },
  { a: "Cats purr for reasons other than happiness.", b: "Purring may also occur when they're stressed or unwell." },
  { a: "Regular grooming does more than keep pets looking good.", b: "It also helps detect lumps, parasites, and skin issues early." },
  { a: "A tired dog is often a well-behaved dog.", b: "Exercise can help reduce destructive behaviours." },
  { a: "Cats often prefer clean litter trays.", b: "Keeping them spotless can help prevent accidents around the home." },
  { a: "Senior pets still love learning.", b: "Old dogs really can learn new tricks." },
  { a: "Ear infections are common in many breeds.", b: "Regular ear checks can help catch problems early." },
  { a: "Some pets suffer from anxiety.", b: "Changes in routine, loud noises, or being left alone can trigger stress." },
  { a: "Chocolate is toxic to dogs.", b: "Even small amounts can become an emergency." },
  { a: "Cats can jump up to six times their body length.", b: "Their powerful muscles make them incredible athletes." },
  { a: "Pets can get bored eating from the same bowl every day.", b: "Food puzzles can make mealtime more fun." },
  { a: "Many pets are masters at hiding illness.", b: "Regular health checks are important, even when they seem fine." },
  { a: "A pet's nose temperature doesn't indicate health.", b: "A warm nose doesn't necessarily mean they're sick." },
  { a: "Exercise needs vary greatly between breeds.", b: "Some dogs are happy with a stroll while others need hours of activity." },
  { a: "Cats spend up to half their waking hours grooming.", b: "Grooming helps regulate temperature and maintain healthy skin." },
  { a: "Car restraints help protect pets during travel.", b: "They can also reduce distractions for drivers." },
  { a: "Many pets enjoy listening to music.", b: "Certain sounds may help them relax during stressful times." },
  { a: "Dogs can dream.", b: "Those twitching paws during sleep may be signs they're dreaming." },
  { a: "Scratching is normal cat behaviour.", b: "Scratching posts help protect both claws and furniture." },
  { a: "Water fountains encourage many cats to drink more.", b: "Flowing water appeals to their natural instincts." },
  { a: "Older pets may need more frequent check-ups.", b: "Early detection becomes even more important with age." },
  { a: "Pets can experience seasonal allergies.", b: "Itchy skin and excessive licking are common signs." },
  { a: "Some human foods are dangerous for pets.", b: "Grapes, onions, and xylitol can be highly toxic." },
  { a: "Dogs read human emotions surprisingly well.", b: "They often respond to changes in our voice and facial expressions." },
  { a: "Cats use slow blinking as a sign of trust.", b: "A slow blink back is often called a cat kiss." },
  { a: "Boredom can contribute to destructive behaviour.", b: "Enrichment and playtime help channel energy positively." },
  { a: "Pets benefit from training throughout life.", b: "Learning new skills provides valuable mental exercise." },
  { a: "Many pets dislike sudden changes.", b: "Introducing new foods and routines gradually can ease stress." },
  { a: "Prevention is often less expensive than emergency treatment.", b: "Routine care can save money and improve quality of life." },
  { a: "Your pet's health is about more than just vaccines.", b: "Nutrition, exercise, dental care, and regular check-ups all play a role." },
];
