// Pet insurance providers by country. Extend with more countries over time.
// Used by the pet profile Ownership card (insurance provider dropdown).

export const INSURANCE_PROVIDERS_AU = [
  "ahm Pet Insurance",
  "AAMI Pet Insurance",
  "ANZ Pet Insurance",
  "APIA Pet Insurance",
  "Australian Seniors Pet Insurance",
  "Australian Unity Pet Insurance",
  "Bank of Melbourne Pet Insurance",
  "BankSA Pet Insurance",
  "Bankwest Pet Insurance",
  "Bow Wow Meow Pet Insurance",
  "Bupa Pet Insurance",
  "Budget Direct Pet Insurance",
  "CBA Pet Insurance",
  "Coles Pet Insurance",
  "Everyday Pet Insurance",
  "Fetch Pet Insurance",
  "GIO Pet Insurance",
  "Guardian Pet Insurance",
  "Guide Dogs Pet Insurance",
  "HCF Pet Insurance",
  "Health.com.au Pet Insurance",
  "Hollard Pet Insurance",
  "Knose Pet Insurance",
  "Medibank Pet Insurance",
  "myPet Insurance",
  "NAB Pet Insurance",
  "NRMA Pet Insurance",
  "PD Insurance",
  "Pet Insurance Australia",
  "Petcover",
  "Petplan Australia",
  "Petsy Pet Insurance",
  "PIA Pet Insurance",
  "Prime Pet Insurance",
  "Qantas Pet Insurance",
  "RAA Pet Insurance",
  "RAC Pet Insurance",
  "RACQ Pet Insurance",
  "RACV Pet Insurance",
  "RAC WA Pet Insurance",
  "Real Pet Insurance",
  "RSPCA Pet Insurance",
  "Seniors Pet Insurance",
  "Shannons Pet Insurance",
  "St.George Pet Insurance",
  "Suncorp Pet Insurance",
  "Virgin Money Pet Insurance",
  "Westpac Pet Insurance",
  "Woolworths Pet Insurance",
  "Youi Pet Insurance",
] as const;

// Default to AU for now. Later: pick list by the owner's country.
export const INSURANCE_PROVIDERS = INSURANCE_PROVIDERS_AU;
