/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/account` | `/account`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/pets` | `/pets`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/referrals` | `/referrals`; params?: Router.UnknownInputParams; } | { pathname: `/pet/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/referral/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/account` | `/account`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/pets` | `/pets`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/referrals` | `/referrals`; params?: Router.UnknownOutputParams; } | { pathname: `/pet/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/referral/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/account${`?${string}` | `#${string}` | ''}` | `/account${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/pets${`?${string}` | `#${string}` | ''}` | `/pets${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/referrals${`?${string}` | `#${string}` | ''}` | `/referrals${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/account` | `/account`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/pets` | `/pets`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/referrals` | `/referrals`; params?: Router.UnknownInputParams; } | `/pet/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/referral/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/pet/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/referral/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
